### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel-graphql-api#2]
### Description

Create a docker image for this tool in order for users to deploy to production

### Motivation

Production deployment should be made easier

**Comment by magnusbaeck** [comment]
Since the package provides both the GraphQL API and an RabbitMQ-to-MongoDB bridge, perhaps two dockerfiles are in order? Technically we could have a default ENTRYPOINT statement that points to wsgi.py and people can override that with `--entrypoint ...` when they start the container to use storage.py but that doesn't give me any warm fuzzies. The drawback is the double maintenance of the dockerfiles.
